tier_keys:
  google:
    free: ""
    paid: ""

clients:
  Test_Client:
    name: "Test_Client"  # <-- FIX: Changed from "modicare"
    tier: "paid"
    service: "google"

  oriflame:
    name: "oriflame"      # <-- FIX: Changed from "modicare"
    tier: "free"
    service: "google"