# config.yaml

tier_keys:
  google:
    free: ""
    paid: ""

clients:
  modicare:
    name: "modicare"
    tier: "paid"
    service: "google"

  oriflame:
    name: "modicare"
    tier: "free"
    service: "google"